js:
  - https://unpkg.zhimg.com/jquery@3.5.1/dist/jquery.min.js
  - https://lib.baomitu.com/popper.js/2.9.3/umd/popper.min.js
  - https://lib.baomitu.com/twitter-bootstrap/4.6.0/js/bootstrap.min.js
  - /assets/js/shards.min.js
  - https://unpkg.zhimg.com/tablesorter@2.30.7/dist/js/jquery.tablesorter.min.js
  - https://unpkg.zhimg.com/lz-string@1.4.4/libs/lz-string.min.js
  - https://hm.baidu.com/hm.js?4158ba36cc7a19f9ba8a547fa33b69da
  - https://lib.baomitu.com/vue/2.6.14/vue.min.js
  - https://lib.baomitu.com/d3/7.0.1/d3.min.js
  - https://lib.baomitu.com/c3/0.7.20/c3.min.js
  - https://lib.baomitu.com/echarts/5.2.0/echarts.min.js
  - https://lib.baomitu.com/showdown/1.9.1/showdown.min.js
css:
  - https://lib.baomitu.com/twitter-bootstrap/4.6.0/css/bootstrap.min.css
  - https://unpkg.zhimg.com/@fortawesome/fontawesome-free@5.7.0/css/all.min.css
  - /assets/css/common.css
  - /resources/akdata.css
  - /assets/css/c3.css
  - /assets/css/shards.css

modules:
  - /assets/js/common.js
  - /resources/akdata.js?ver=211220
