js:
  - https://unpkg.zhimg.com/jquery@3.3.1/dist/jquery.min.js
  - https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js
  - https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/js/bootstrap.min.js
  - https://unpkg.zhimg.com/tablesorter@2.30.7/dist/js/jquery.tablesorter.min.js
  - https://unpkg.zhimg.com/lz-string@1.4.4/libs/lz-string.min.js
  - https://hm.baidu.com/hm.js?4158ba36cc7a19f9ba8a547fa33b69da
  - https://cdn.jsdelivr.net/npm/vue/dist/vue.js
  - https://d3js.org/d3.v5.min.js
  - https://cdn.jsdelivr.net/npm/c3@0.7.15/c3.min.js
css:
  - https://libs.cdnjs.net/twitter-bootstrap/4.5.0/css/bootstrap.min.css
  - https://unpkg.zhimg.com/@fortawesome/fontawesome-free@5.7.0/css/all.min.css
  - /assets/css/common.css
  - /resources/akdata.css
  - /assets/css/c3.css

modules:
  - /assets/js/common.js
  - /resources/akdata.js